from .PartOfSpeech import PartOfSpeech
from .RelationType import RelationType
from .IWiktionary import IWiktionary
from .IPronunciation import IPronunciation
from .IQuotation import IQuotation
from .IWikiString import IWikiString
from .IWiktionaryCollection import IWiktionaryCollection
from .WiktionaryException import WiktionaryException
from .IWiktionarySense import IWiktionarySense
from .IWiktionaryEntry import IWiktionaryEntry
from .IWiktionaryPage import IWiktionaryPage
from .IWiktionaryEdition import IWiktionaryEdition
from .IWiktionaryRelation import IWiktionaryRelation
from .IWiktionaryExample import IWiktionaryExample
from .IWiktionaryWordForm import IWiktionaryWordForm
from .IWiktionaryTranslation import IWiktionaryTranslation
from .WiktionaryFormatter import WiktionaryFormatter
